on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Copy to artifacts path
      run:  |
        # ls -la $GITHUB_WORKSPACE/module\ 7/
        # moduleSevenSourcePath="$GITHUB_WORKSPACE/module\ 7/"
        # ls -la "$moduleSevenSourcePath"
        # moduleSevenArtifactsPath="$RUNNER_TEMP/module7-artifacts"
        mkdir -p $RUNNER_TEMP/module7-artifacts
        cp -avR $GITHUB_WORKSPACE/module\ 7/ $RUNNER_TEMP/module7-artifacts 
      
      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: $RUNNER_TEMP/module7-artifacts/main.bicep
        failOnStdErr: false
