on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Copy to artifacts path
      run:  |
        ls -la $GITHUB_WORKSPACE/module\ 7/
        moduleSevenSourcePath="${GITHUB_WORKSPACE}/module\ 7/"
        moduleSevenArtifactsPath="${RUNNER_TEMP}/module7-artifacts"
        mkdir -p "$moduleSevenArtifactsPath"
        cp -avR "$moduleSevenSourcePath" "$moduleSevenArtifactsPath"
        
      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ${RUNNER_TEMP}/module7-artifacts/main.bicep
        failOnStdErr: false
